<?php
// tools 
// https://apps.timwhitlock.info/unicode/inspect
// https://www.lexilogos.com/keyboard/arabic.htm
// https://www.branah.com/arabic

$GLOBALS['charPegonList'] = [
    ['ا', 'A', 'ALIF'],
    ['ب', 'b', 'BA'],
    ['ت', 't', 'TAK'],
    ['ث', 'TS', 'TSA'],
    ['ج', 'j', 'JIM'],
    ['ح', 'H', 'HAK'],
    ['خ', 'KH', 'KHOK'],
    ['د', 'd', 'DAL'],
    ['ذ', 'DZ', 'DZAL'],
    ['ر', 'r', 'ROK'],
    ['ز', 'z', 'ZAI'],
    ['س', 's', 'SIN'],
    ['ش', 'SY', 'SYIN'],
    ['ص', 'SH', 'SHOD'],
    ['ض', 'DH', 'DHOD'],
    ['ط', 'TH', 'TOK'],
    ['ظ', 'ZH', 'DZOK'],
    ['ع', 'E', 'AIN'],
    ['غ', 'GH', 'GHOIN'],
    ['ف', 'f', 'FAK'],
    ['ق', 'q', 'QOF'],
    ['ك', 'k', 'KAF'],
    ['ل', 'l', 'LAM'],
    ['م', 'm', 'MIM'],
    ['ن', 'n', 'NUN'],
    ['و', 'w', 'WAWU'],
    ['ي', 'y', 'YAK'],
    ['ه', 'h', 'HA'],
    ['أ', 'M', 'HAMZAH_ALIF_ATAS'],
    ['إ', 'W', 'HAMZAH_ALIF_BAWAH'],
    ['ؤ', 'U', 'HAMZAH_WAWU'],
    ['ئ', 'I', 'HAMZAH_YAK'],
    ['ء', 'O', 'HAMZAH_MUSTAQIL'],
    ['ى', 'Y', 'ALIF_LAYYINAH'],
    ['ة', 'T', 'TAK_MARBUTOH'],
    ['چ', 'c', 'CE'],
    ['ڮ', 'g', 'GE'],
    ['ڤ', 'p', 'PE'],
    ['آ', 'B', 'HAMZAH_MAD'],
    ['َ', '.-', 'FATHAH'],
    ['ً', '.--', 'FATHAIN'],
    ['ُ', '.^', 'DHUMMAH'],
    ['ٌ', '.^^', 'DHUMMATAIN'],
    ['ِ', '._', 'KASROH'],
    ['ٍ', '.__', 'KASROTAIN'],
    ['ْ', '.‘', 'SUKUN'],
    ['ّ', '.“', 'TASYDID'],
    ['ٰ', './', 'ALIF_MAD_UP'],
    ['ٖ', '.\\', 'ALIF_MAD_DOWN'],
    [' ', 'SPASI', 'SPASI'],
    ['١', '', 'SATU'],
    ['٢', '', 'DUA'],
    ['٣', '', 'TIGA'],
    ['٤', '', 'EMPAT'],
    ['٥', '', 'LIMA'],
    ['٦', '', 'ENAM'],
    ['٧', '', 'TUJUH'],
    ['٨', '', 'DELAPAN'],
    ['٩', '', 'SEMBILAN'],
    ['٠', '', 'NOL'],
    ['.', '', 'TITIK'],
    ['،', '', 'KOMA'],
    ['ـ', '', 'TATWIL'],
];;